name: Comment on Issue Close

on:
  issues:
    types: [closed]

permissions:
  issues: write

jobs:
  greet-on-close:
    runs-on: ubuntu-latest

    steps:
      - name: Greet User
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            const issueCreator = issue.user.login;
            const issueNumber = issue.number;
            
            const closer = context.payload.sender.login;
            const wasClosedByCreator = issueCreator === closer;
            
            let greetingMessage = `👋 Hello @${issueCreator}!\n\n`;
            greetingMessage += `Thank you for reporting this issue. Issue #${issueNumber} has been closed`;
            
            if (!wasClosedByCreator) {
              greetingMessage += ` by @${closer}`;
            }
            
            greetingMessage += `. If you have any questions or need further assistance, please don't hesitate to reach out!\n\n`;
            greetingMessage += `We appreciate your contribution to making our project better! 🙌`;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.name,
              issue_number: issueNumber,
              body: greetingMessage
            });