name: Validate Issue Template

on:
  issues:
    types:
      - opened
      - edited

permissions:
  issues: write

jobs:
  validate-template:
    runs-on: ubuntu-latest

    steps:
      - name: Validate Issue Template
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue
 
            // Check if the issue uses our template form
            if (!issue.body.includes('### ISSUE NAME')) {
              const errorMessage = `
              👋 Hello @${issue.user.login},
              
              Thank you for creating this issue! However, it seems you haven't used our issue template form.
              Please create a new issue using the issue template form provided.
              
              You can do this by:
              1. Going to the Issues tab
              2. Clicking "New Issue"
              3. Selecting "Contributor Issue Form"
              
              This helps us better organize and address your concerns.
              `;
              
              // Add comment to the issue
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.name,
                issue_number: issue.number,
                body: errorMessage.trim()
              });
              
              // Close the issue as it doesn't use the template
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.name,
                issue_number: issue.number,
                state: 'closed',
                state_reason: 'not_planned'
              });
              
              core.setFailed('Issue was not created using the template form');
            } else {

              // Issue uses the template form
              // We can add additional labels if needed
              
              if (!issue.labels.some(label => label.name === 'needs triage')) {
                await github.rest.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.name,
                  issue_number: issue.number,
                  labels: ['needs triage']
                });
              }
            }